# Generated by Django 4.1.3 on 2024-12-04 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='bio',
            field=models.CharField(max_length=55),
        ),
    ]
