# Generated by Django 4.1.3 on 2024-12-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0002_alter_artist_age_alter_artist_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunaapi.artist'),
        ),
        migrations.AlterField(
            model_name='song_genre',
            name='song_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='tunaapi.song'),
        ),
    ]
