# Generated by Django 4.1.3 on 2024-12-07 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0003_alter_song_artist_id_alter_song_genre_song_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song_genre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genre_songs', to='tunaapi.genre'),
        ),
    ]
