# Generated by Django 4.1.3 on 2024-12-10 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0004_alter_song_genre_genre_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song_genre',
            new_name='SongGenre',
        ),
    ]
