# Generated by Django 4.1.3 on 2024-12-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0005_rename_song_genre_songgenre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='artist_id',
            new_name='artist',
        ),
    ]
