# Generated by Django 4.1.3 on 2024-12-10 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0006_rename_artist_id_song_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenre',
            name='genre_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genresongs', to='tunaapi.genre'),
        ),
    ]
