# Generated by Django 4.1.3 on 2024-12-10 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0007_alter_songgenre_genre_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='songgenre',
            old_name='genre_id',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='songgenre',
            old_name='song_id',
            new_name='song',
        ),
    ]
