# Generated by Django 4.1.3 on 2024-12-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunaapi', '0008_rename_genre_id_songgenre_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songgenre',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genresforsongs', to='tunaapi.song'),
        ),
    ]
